### ISSUE TITLE
JSON file 404-ing

### ISSUE THREAD

**Issue by aarongustafson** [Freizeitler/cocktail-o-clock-10k#1]
I figured out why: https://blogs.msdn.microsoft.com/africaapps/2013/06/07/how-to-serve-static-json-files-from-a-windows-azure-website/

Can you add that web.config?

PS - Does this project work without JavaScript?

**Comment by Freizeitler** [comment]
Ah, ok. I added the web.config. And yes, it just offers a basic experience without JS, but the UI is working properly. It's set up with pure HTML/CSS. Check it out here: http://www.freizeitler.de/cocktail-app/
Hope that's fine for the contest.

**Comment by aarongustafson** [comment]
Working: http://cocktail-o-clock-10k1-10kapart2016.azurewebsites.net/
